name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up the latest Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install packages
        run: make install
      - name: Lint
        run: make lint
      - name: Test
        run: make test
      - name: Format
        run: make format
      - name: Deploy
        run: make deploy
